language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: CZIt4mj0leLH9uc3RjG2Yin2kbUa5zaLfPQfZRNRFi8ww/ZyH8N1GTch3LCtNcErWIBdba+Xo1klia1Ae+w7RGY4otvnL9BZLInX00Lb7n1M/pQ+vgA3NtFSqED+9nRUbY4xx4BMbSwOfO41ichTawFc5Up7pwe9gxF2xxgpbOOChRrqW+/eGat43SwNdvnZfKCCRSw3y0eNs+Ufc3sZ268zGxmH6j9ro7zcIP88aNktVYjQSPTkYMmaX7nvlaX0clIH4AMB3I1bh+vXWOnYlhyCZqca9McsDsfv15NjKF5vaaDZtQ5kZnfcY8mcprLuH6ONrVP0kCgl8hm8G/9jPRnyDGJhSdsIGw+1k0sckMXu6znuuT2+ZoP9Yv5L/kmEXKh46Dfvsq+o8saFw7jKtvYidMqMxGquSa/GlrhAcr12gNB9mtQwD/6KEWmeapV0Fa4zjMGazT4hBoWHTcHvhbCzTAfprXhB/XLNBmawTr6frPFMcvgiyk1fTVu6SXTXZJ7m6pggK8hRcqnuae89jYNFUMlSRQ8/uP3rRnFg6cr5eIm1YVbAkWhw+mKA1YdWul4IwMkKxuzRRhN7X4Yzz8cOEItoCA1sc17Ztx74kVOPTfX3BCw9Nk3CPpPH6df0qqAdJjbthH7F3NK36fGHwMlH67uzMTssbd89jPgGXCA=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-frontend
    branch: prototype