language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: IwVSr6Tx5w5uTmo5uO1pdhy4I+bEuY4okgQzh/OoD+O593jToRsOpEIWlhrjelZcCNSnrP/3fQskpgFFwCy7nDtocTdTiY8izCVvljET6WIHcjY65uNItFa2r8/7vHx2prcx4HDr+wByavRKhHbBtjlbMTfJSj6J27MLg+Mq/iWAsejVFYBtR5VpZDodb5W9IriNwtCu5QlouPi+hoIKSBlgCFLHlqHv1h4jMK8qaFJKofE/uv84hrAdgblOi0PHODVo7QXNCmCzpHNK0PWtY1q4X+qBXUDqMemjKajIENjH9K4RP+j3pndAhn0Dj/j8zVcvIJtQZz5aWibEOT8dOVDnRN+OA19E5/JTKfJlmxpqXPC56CyxrnUJYmpwd0sg5VOl6CH2lOBK9tQRogLm8zsa+oXtSDCPJlPcDdmnb6oMRlE2692l4lLTdWyYEWpkLRHVto49fHvsL6tc+jUpEJ9feH2SnGQr0Axh8Zw1k7HP0nYx67t9GJ2uZUrcVHclcqes6eVpuNUVbeYwmZ/ogdGZ40sSLLnze6pVfhrcUOROw1GZrDFfMcxUSrTDCIfVupiSZLcCmpQ35IMzBzPNBnXJSji6QwBMtjpenQ6IN7DYMdYb2fjpqLkGuZemJkliiFKpsg+FLHL2OGLp7vCD5vrmOMVa97Td4EAvQlaC5IA=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-frontend
    branch: prototype
