language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: RFbgqyUqMBc/2HEMbh/HYKRRR/tDY3ZStqMCgVyQn4Qy4lv8hU3CVtnZWGorxNVHW4UeFfIVkN/3EAey/r0ouMP6+Fo+Yz9HGUl+F3LvpEa3h3GukdUsGScd99e/No4BjR7ZEaxyFOusEiUGUFjHB9cda8EN8UJ/w7jL1ov8YwX2wXL9NFUMfVITNNWVbjnSa6pxFfE8mRxzSHwDoHE0rpfxCmTxxJwMuLgiDxYLWB5CGOWf/8Klb+7RSv1l7yEESXDZ+TW32TUt0LOQNztBvNMeay/XBzAl0/n680bP/uLqu1Zqbddoe0h+FGWjcnhX2McLi2cppC1q2rIG+5tzlezQ4FNNF80C1Xf9maHxaY1KsLj2A89VJ6isbSQX2lCqV7/BpQM4zv0dsHwfbfATBUaEngECR+lxHSLystrgj6WyikULuqpOgPuIXZb2bRIUj6U2dDhQEaead6wEVUuicjzFRy6mc12UHRTOjsLoww4W3LILZt4HWkndbK/Kt9rteoyztC/Xrikda6Nec1DqynzJvm45kGgtgaDDYW86ubCrWxC/N6Hh1Fqxsign/Z8HT059lxvp+VSWF82rYJtTQvElyqVFbHtp65c/YulMnOu1QqJq4Lxuz3k2jq+LAlc6PRWBDrZthdJQ0bsmzTpBqhou8xd6plM2rPrOZhXXfBs=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-frontend
    branch: prototype
