language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: Q9A9T4ssHYGtM89sthT7C6rQ/tdFiXW8d5L5Qzs+sMPqaHaZQKKa6+jW/fyNN7T2RLOlGSsZBXf/jQbnLJKH0wQg0pqM27g36XyK3KqN0T1ihOfCNUzFF7/ARtu00oD/5OyN+I15sDaici305w1jHPmnh0n21dB0pNb115+f85UNbxJdy/cqKxufdRexN9SSp13VYnY+TK1UTL1loUP/S/5OG84G1usq1ItMNwR9sz92NH20wuvoJmAInQFVaJk7552m/8KZttpDQJTdvuu3OeyOLcO1bU1LUUfjAkW2zfoE8M10I5l4plzvMbgcT3ldrnPaEvE5sLgQB/tUSyVEhkW/zD0AZgoVvwvyiKC+hsnN+uecYE87PRBH0FUE77WS8royGsTAFqF7JI4+d6CJdBpQzgfSDBfVCg8EbEa13l6Pgc7jdPDJT//0f5RdqubS3OGtho2hF90EEw+saoTJUso1AfaEWNCppH6H6fmbfMq4BoE5ktKAMFTR1hwihN9Wq7SS5HyGwWSlareso3jhg00An/LqJSJSFV+iUjltKztCNiUBMd295H+TFSelRWPtIypod53cRUtxxMeKI43N9S9SQMasnR/9BH/jfqsGVjVue1l3Y6K+T8uQrNUqLIGrWZqm51PvDRKZBDK0ztDMF5WbJTmVcKaBKywthOLb8WU=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-frontend
    branch: prototype
