language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: OQO9Q1wnq9YAXtsUgU7MbTb67Tvz+5PtcnSwcT/Ev8VynPcLH38VOJAktUKwzPsjJhUvY+2Q6MwsGaYFcqpn5yiiCuMe8XiTTikLKqI+XgZZIW95Tl44Sa1JBN6rh0o4KhbMuZ4HYOo4JYitXwwOJcVzqVwD/UKq+jOJ7n2NBXhF1d8pN26hY4HJ5GBRmhmFAG1+DkpcU861zYf+XXrspaCHZgzg2MvmIcQNHpkSEud5VlSPs2zaVOjNI9xhh8arpu5NnK1YCHRuXw41dOybxhYMkZ8LDxF12zceluzdyUhcnw9kowKcx4D3CsRudJimz2klGSPcfA/MgDwJpltdfUJ0Ja+hXVhIr9KWjQgngbxEaSn2+I8NUbLz39Mo0bH1x8jWGCLq6qU2BfCpRLcPh0jc7BL4oZujP6tn9SCaqm4f6MqSSpDHODgWBgePDaWhTt15h5bUBWXn362n10f99Y0SEGTlWocwvMxjepLqhrbQhPBktjV7Ui7VmqM2J2lOHQHfxBS4ATiBAR0qntmux24TZqDOFRUmZR5RQUQJBa6WM9MjfdpQh3bYYt+6ripfEyPc9ARUxhFNZYFyjgyZct27ZRQbXPUKiJJ0HSsUi05eDgRx9FoDqiBZCK5znxYTi69GndtQsAjHNp1vRR9aQNaFzuoM/hr92u5lAxBQiGQ=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-frontend
    branch: prototype